####################################################################################
###################################DataSource Config################################
####################################################################################
spring:
  datasource:
    # JDBC 配置
    type: com.alibaba.druid.pool.DruidDataSource
    #    schema:
    #      - classpath:/db/schema-mysql.sql
    #    data:
    #      - classpath:/db/data-mysql.sql
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.30.15:1521:orcl
    username: ly_cloud_xtgl
    password: ly_cloud_xtgl
    druid:
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      max-open-prepared-statements: 20
      validation-query: SELECT 'x' from dual
      validation-query-timeout: 30000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 300000
      filters: stat,wall,log4j
      # 监控配置
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter:
        enabled: true  #是否启用StatFilter默认值true
        url-pattern: /druid/*
        #        exclusions: *.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
        session-stat-enable: true
        session-stat-max-count: 10
        principal-session-name:
        principal-cookie-name:
        profile-enable: true
      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        enabled: true #是否启用StatViewServlet默认值true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
        allow:
        deny:
      # Spring监控配置，说明请参考Druid Github Wiki，配置_Druid和Spring关联监控配置
      # 如果spring.datasource.druid.aop-patterns要代理的类没有定义interface请设置spring.aop.proxy-target-class=true
      #aop-patterns: #Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
  #########################################################################################################
  ##########################################spring boot redis #############################################
  #########################################################################################################
  redis:
    database: 0           # Redis数据库索引（默认为0）
    host: 192.168.30.23   # Redis服务器地址
    port: 6379            # Redis服务器连接端口
    password:      #Redis服务器连接密码（默认为空）
    timeout: 0            # 连接超时时间（毫秒）
    pool:
      max-idle: 8         # 连接池中的最大空闲连接
      min-idle: 1         # 连接池中的最小空闲连接
      max-active: 8       # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1        # 连接池最大阻塞等待时间（使用负值表示没有限制）
  #    sentinel:
  #      master:
  #      nodes:
  #############################################################################################
  ######################################## MQ config ##########################################
  #############################################################################################
  rabbitmq:
    host: 192.168.30.23
    port: 5672
    username: admin
    password: 123456
####################################################################################
###################################MyBatis Plus Config##############################
####################################################################################
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.example.demo.**.entity
  #  typeEnumsPackage: com.ly.cloud.domain.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    logic-delete-value: 1
    logic-not-delete-value: 0
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.mybatisplus.mapper.MetaObjectHandler
    #自定义SQL注入器 逻辑删除SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
#############################################################################################
######################################### feign 配置 ##########################################
#############################################################################################
feign:
  hystrix:
    enabled: true